name: flutter_shooting_game
description: flame 엔진을 이용한 슈팅 게임
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/bullet/
    - assets/images/enemy/
    - assets/images/item/
    - assets/images/player/

  uses-material-design: true
